name: foundational_nature_ai
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - exceptiongroup=1.2.0
  - frozenlist=1.4.1
  - greenlet=3.0.3
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - langchain=0.2.6
  - langchain-core=0.2.11
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.84
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - multidict=6.0.5
  - ncurses=6.5
  - openssl=3.3.1
  - orjson=3.10.6
  - pip=24.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pysocks=1.7.1
  - python=3.12.4
  - python_abi=3.12
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=70.1.1
  - sniffio=1.3.1
  - sqlalchemy=2.0.31
  - tenacity=8.5.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asgiref==3.8.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.15.0
      - backoff==2.2.1
      - bcrypt==4.1.3
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - build==1.2.1
      - cachetools==5.3.3
      - certifi==2024.7.4
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - coloredlogs==15.0.1
      - comm==0.2.2
      - dataclasses-json==0.6.7
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - distro==1.9.0
      - dnspython==2.6.1
      - docstring-parser==0.16
      - email-validator==2.2.0
      - executing==2.0.1
      - faiss-cpu==1.8.0.post1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - geopandas==1.0.1
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.1
      - google-api-python-client==2.136.0
      - google-auth==2.31.0
      - google-auth-httplib2==0.2.0
      - google-cloud-aiplatform==1.58.0
      - google-cloud-bigquery==3.25.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.3
      - google-cloud-storage==2.17.0
      - google-crc32c==1.5.0
      - google-generativeai==0.7.1
      - google-resumable-media==2.7.1
      - googleapis-common-protos==1.63.2
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.64.1
      - grpcio-status==1.62.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - humanfriendly==10.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-code-formatter==2.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kubernetes==30.1.0
      - langchain-community==0.2.6
      - langchain-google-genai==1.0.7
      - langchain-google-vertexai==1.0.6
      - langchain-ollama==0.1.1
      - langchain-openai==0.1.14
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy
      - oauthlib==3.2.2
      - onnxruntime==1.18.1
      - openai==1.35.10
      - opentelemetry-api==1.25.0
      - opentelemetry-exporter-otlp-proto-common==1.25.0
      - opentelemetry-exporter-otlp-proto-grpc==1.25.0
      - opentelemetry-instrumentation==0.46b0
      - opentelemetry-instrumentation-asgi==0.46b0
      - opentelemetry-instrumentation-fastapi==0.46b0
      - opentelemetry-proto==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - opentelemetry-util-http==0.46b0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - polars==1.1.0
      - posthog==3.5.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - proto-plus==1.24.0
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.18.0
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pypdf==4.2.0
      - pypika==0.48.9
      - pyproj==3.6.1
      - pyproject-hooks==1.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rasterio==1.3.10
      - referencing==0.35.1
      - regex==2024.5.15
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rioxarray==0.15.7
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.5.1
      - send2trash==1.8.3
      - shapely==2.0.4
      - shellingham==1.5.4
      - six==1.16.0
      - snuggs==1.4.7
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.37.2
      - sympy==1.13.0
      - terminado==0.18.1
      - tiktoken==0.7.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - widgetsnbextension==4.0.11
      - wikipedia==1.4.0
      - wrapt==1.16.0
      - xarray==2024.6.0
      - zipp==3.19.2
